from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
import yt_dlp
import json
import time
import sys
import os
import subprocess
import sqlite3
import time 

port = int(sys.argv[1]) if len(sys.argv) > 1 else 8891
cookies = sys.argv[2] if len(sys.argv) > 2 else "convertCookies2.txt"

print(f"cookies file: {cookies}")
print(f"cookies exists: {os.path.exists(cookies)}")
print(f"cookies size: {os.path.getsize(cookies) if os.path.exists(cookies) else 'N/A'}")


class Handler(BaseHTTPRequestHandler):

    def convert_firefox_cookies(db_path, output_path):
    # Подключаемся к базе данных
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        # Запрос данных из таблицы moz_cookies
        cursor.execute("SELECT host, isHttpOnly, path, isSecure, expiry, name, value FROM moz_cookies")
        rows = cursor.fetchall()

        with open(output_path, 'w', encoding='utf-8', newline='\n') as f:
            # Заголовок, который ожидает yt-dlp
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by yt-dlp.  Do not edit.\n\n")

            for row in rows:
                host, isHttpOnly, path, isSecure, expiry, name, value = row

                # Преобразование логических значений в TRUE/FALSE
                include_subdomains = "TRUE" if host.startswith(".") else "FALSE"
                secure = "TRUE" if isSecure else "FALSE"

                # Запись строки в формате Netscape
                # Host | IncludeSubdomains | Path | Secure | Expiry | Name | Value
                f.write(f"{host}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

        conn.close()
        print(f"Готово! Файл сохранен в: {output_path}")


    def warmup():
        print("warming up yt-dlp...")
        try:
            result = subprocess.run([
                r'C:\Users\karas\Desktop\папка под гошник\yt-dlp.exe',
                '--js-runtimes', r'node:C:\Program Files\nodejs\node.exe',
                '--remote-components', 'ejs:github',
                '--cookies', cookies,
                # '--extractor-args', 'youtube:player_client=android',
                # '--user-agent', 'Mozilla/5.0 (Linux; Android 12; SM-S906N Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36',
                '-f', 'bestaudio/best',
                '--get-url',
                # '-q',
                # '--no-warnings',
                'https://www.youtube.com/watch?v=OPXUeeFXc90'
            ], capture_output=True, text=True, timeout=60)
            
            if result.stdout.strip():
                print("yt-dlp warmed up!")
            else:
                print(f"warmup error: {result.stderr[:200]}")
        except Exception as e:
            print(f"warmup error: {e}")

    def do_GET(self):
        parsed = urlparse(self.path)
        params = parse_qs(parsed.query)
        
        if 'url' not in params:
            self.send_response(400)
            self.end_headers()
            return
        
        yt_url = params['url'][0]
        print(f"resolving: {yt_url}")
        
        start = time.time()
        try:
            result = subprocess.run([
                r'C:\Users\karas\Desktop\папка под гошник\yt-dlp.exe',
                '--js-runtimes', r'node:C:\Program Files\nodejs\node.exe',
                '--remote-components', 'ejs:github',
                '--cookies', cookies,
                '-f', 'bestaudio/best',
                '--get-url',
                yt_url
            ], capture_output=True, text=True, timeout=30)
            
            audio_url = result.stdout.strip()
            elapsed = time.time() - start
            print(f"resolved in {elapsed:.2f}s")
            print(f"stdout: '{audio_url}'")
            print(f"stderr: '{result.stderr}'")
            
            if not audio_url:
                print(f"error: {result.stderr}")
                self.send_response(500)
                self.end_headers()
                self.wfile.write(result.stderr.encode())
                return
                
            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({'url': audio_url, 'duration': 0}).encode())
            
        except Exception as e:
            print(f"error: {e}")
            self.send_response(500)
            self.end_headers()
            self.wfile.write(str(e).encode())
            
    def log_message(self, format, *args):
        pass # тишина в консоли
    # warmup()
    

Handler.convert_firefox_cookies(r'C:\Users\karas\AppData\Roaming\Mozilla\Firefox\Profiles\jT7Um0X6.Profile 1\cookies.sqlite', 
    r'C:\Users\karas\Desktop\папка под гошник\convertCookies2.txt')    
Handler.warmup()
print(f"yt-dlp server on :{port}")
HTTPServer(('localhost', port), Handler).serve_forever()



